### ISSUE TITLE
Key Error Running Examples

### ISSUE THREAD

**Issue by dzalkind** [tsdat/tsdat#2] opened 2021-07-01 19:58 UTC
Hi There!

@maxwellevin , this is the key error I mentioned over email:

`
(dm-env) dzalkind@ssl-vpn-10-10-140-19 tsdat % python3 examples/a2e_lidar_ingest/run_pipeline.py 
Traceback (most recent call last):
  File "examples/a2e_lidar_ingest/run_pipeline.py", line 18, in <module>
    main()
  File "examples/a2e_lidar_ingest/run_pipeline.py", line 14, in main
    run_pipeline()
  File "/Users/dzalkind/Tools/tsdat/examples/a2e_lidar_ingest/pipeline/runner.py", line 22, in run_pipeline
    humboldt_pipeline.run(humboldt_raw_file)
  File "/Users/dzalkind/Tools/tsdat/tsdat/pipeline/ingest_pipeline.py", line 44, in run
    dataset = self.store_and_reopen_dataset(dataset)
  File "/Users/dzalkind/Tools/tsdat/tsdat/pipeline/pipeline.py", line 344, in store_and_reopen_dataset
    saved_paths = self.storage.save(dataset)
  File "/Users/dzalkind/Tools/tsdat/tsdat/io/storage.py", line 213, in save
    FileHandler.write(dataset, tmp_path)
  File "/Users/dzalkind/Tools/tsdat/tsdat/io/filehandlers/file_handlers.py", line 101, in write
    handler.write(ds, filename, config, **kwargs)
  File "/Users/dzalkind/Tools/tsdat/tsdat/io/filehandlers/netcdf_handler.py", line 50, in write
    units = variable.attrs['units']
KeyError: 'units'
`

I am running on the master branch with no changes.

It seems to work if I make the following change:

![image001](https://user-images.githubusercontent.com/65573423/124182628-57db8d80-da74-11eb-8fe5-0957c044cc05.png)

Best, Dan

**Comment by maxwellevin** [comment] 2021-07-06 17:57
Hey @dzalkind, thanks for opening this issue. It looks like you are getting the `KeyError` because the `time` variable does not have a `units` attribute. This is strange because it should get units from the `dataset_definition` in the respective pipeline config file for the examples you are running (`examples/a2e_lidar_ingest/config/humboldt_config.yml` and `examples/a2e_lidar_ingest/config/morro_config.yml`).

While it looks like your fix works in this case, I'm not sure if it is preferable because it masks a separate problem (lack of units on time variables) and potentially opens the door for ambiguity in the time values written to disk since we lose the encoding information for the time variable. 

What I'd like to do is identify where we are losing the `units` attribute on the time variable. IIRC it should be added in the `standardize_dataset` function in the `IngestPipeline` class, so you should be able to see it by the time the code reaches the `hook_customize_dataset()` hook. 

To help me debug this, could you provide the python version you are running, along with the versions of installed dependencies?
```
>>> (dm-env) python3 -V
>>> (dm-env) python3 -m pip freeze > dependencies.txt
```

**Comment by dzalkind** [comment] 2021-07-06 20:31
Hey @maxwellevin, 

I am running with
Python 3.7.10 and the dependencies are here:

[dependencies.txt](https://github.com/tsdat/tsdat/files/6772691/dependencies.txt)

**Comment by maxwellevin** [comment] 2021-07-08 17:03
Hey @dzalkind, I was able to reproduce the same error you are getting. I'm listing the steps to reproduce it below:
```
>>> git clone https://github.com/tsdat/tsdat.git
>>> conda create --name dm-env python=3.7.10
>>> conda activate dm-env
>>> (dm-env) pip install -e tsdat
>>> (dm-env) python tsdat/examples/a2e_lidar_ingest/run_pipeline.py
Traceback (most recent call last):
  File "tsdat/examples/a2e_lidar_ingest/run_pipeline.py", line 18, in <module>
    main()
  File "tsdat/examples/a2e_lidar_ingest/run_pipeline.py", line 14, in main
    run_pipeline()
  File "/Users/levi260/sandbox/tsdat/examples/a2e_lidar_ingest/pipeline/runner.py", line 22, in run_pipeline
    humboldt_pipeline.run(humboldt_raw_file)
  File "/Users/levi260/sandbox/tsdat/tsdat/pipeline/ingest_pipeline.py", line 44, in run
    dataset = self.store_and_reopen_dataset(dataset)
  File "/Users/levi260/sandbox/tsdat/tsdat/pipeline/pipeline.py", line 344, in store_and_reopen_dataset
    saved_paths = self.storage.save(dataset)
  File "/Users/levi260/sandbox/tsdat/tsdat/io/storage.py", line 213, in save
    FileHandler.write(dataset, tmp_path)
  File "/Users/levi260/sandbox/tsdat/tsdat/io/filehandlers/file_handlers.py", line 101, in write
    handler.write(ds, filename, config, **kwargs)
  File "/Users/levi260/sandbox/tsdat/tsdat/io/filehandlers/netcdf_handler.py", line 50, in write
    units = variable.attrs['units']
KeyError: 'units'
```

What's interesting is that when I run from my IDE I don't get this error. I tried both VS Code and PyCharm. I'll do a bit more digging, but my guess is that the IDEs I'm using are adding something to the pythonpath that isn't there when running via the terminal. For now, can you try running this from VS Code or PyCharm and see if that resolves the issues you are seeing?

**Comment by dzalkind** [comment] 2021-07-08 17:42
Hey Max,

I am running from VSCode.  What version of python do you usually install with your conda environment?

**Comment by maxwellevin** [comment] 2021-07-08 17:51
I typically run 3.8 or 3.9, but it shouldn't make much of a difference as long as you have at least 3.7.

Do you get the same error if you run this in the VS Code debugger?

**Comment by maxwellevin** [comment] 2021-07-12 17:42
I narrowed down the bug to something going on in `tsdat.qc.handlers.RecordQualityResults`. This `QualityHandler` uses `act-atmos`'s `qcfilter.add_test` function to add a quality variable to record the results of tests on data variables. It looks like there is a bug in this function that causes it to drop the attributes on the coordinate variable dimensioning the variable being tested. I opened https://github.com/ARM-DOE/ACT/issues/347 to address this. 

This seems to only be an issue for recent releases of `act-atmos`. I tried using `act-atmos==0.7.2` and this resolved the problem, so for now you can run 
```
>>> (dm-env) pip install act-atmos==0.7.2
```

and then the examples should run fine. I'll close this Issue once the `act-atmos` issue is resolved.

**Closed** 2021-07-14 20:28 UTC
