### ISSUE TITLE
Clean up Documentation Per Robert's Feedback

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/tsdat#88] opened 2022-05-20 17:35 UTC
- [ ] For the conda env step, user should do that from the local repo directory- this is not mentioned in the RTD guide.
- [ ] Add notes about conda environment not activating correctly and how to fix it.
- [ ] The RTD page does not mention setting the python version before the runner.py demo. Later, the first step in Creating a New Ingest says to open the readme.md in VSC and that doc actually has the steps to set up VSC for python interpreter. So maybe move this step earlier in the tutorial?
- [ ] From that same readme.md, step 4 in opening your repository in VS Code- 0/0 tests passed. So no tests, no green check marks. However, if the user then returns to the instruction in the RTD page, step 2, Navigate to Testing and press play, that works.
- [ ] When making cookies, it appears there are some default or generated suggestions appear to the left of the colon. It’s not clear if just hitting enter accepts these defaults or they actually need to be typed in

**Comment by kefeimo** [comment] 2022-06-09 18:45
- [ ] The RTD page does not mention setting the python version before the runner.py demo. Later, the first step in Creating a New Ingest says to open the readme.md in VSC and that doc actually has the steps to set up VSC for python interpreter. So maybe move this step earlier in the tutorial?

Related text in README:
```
Tell VS Code to use your new conda environment:

Press F1 to bring up the command pane in VS Code
Type Python: Select Interpreter and select it.
Select the newly-created tsdat-pipelines conda environment from the drop-down list.
You may need to refresh the list (cycle icon in the top right) to see it.

Bring up the command pane and type Developer: Reload Window to reload VS Code and ensure the settings changes propagate correctly.
```


- [x] But how to "ensure the settings changes propagate correctly"?
ANS: 
![Image](https://user-images.githubusercontent.com/28743873/172920960-1779b21f-6d3e-41d2-bcec-ce16ca42d15d.png)

**Comment by maxwellevin** [comment] 2022-06-09 19:53
Thanks @kefeimo for picking this up. I'll assign this issue to you

**Comment by kefeimo** [comment] 2022-06-10 17:46
For house-keeping

- [ ] 1.  For the conda env step, user should do that from the local repo directory- this is not mentioned in the RTD guide.
- [ ] 2.  Add notes about conda environment not activating correctly and how to fix it.
- [ ] 3.  The RTD page does not mention setting the python version before the runner.py demo. Later, the first step in Creating a New Ingest says to open the readme.md in VSC and that doc actually has the steps to set up VSC for python interpreter. So maybe move this step earlier in the tutorial?
- [ ] 4.  From that same readme.md, step 4 in opening your repository in VS Code- 0/0 tests passed. So no tests, no green check marks. However, if the user then returns to the instruction in the RTD page, step 2, Navigate to Testing and press play, that works.
- [ ] 5.  When making cookies, it appears there are some default or generated suggestions appear to the left of the colon. It’s not clear if just hitting enter accepts these defaults or they actually need to be typed in

**Comment by kefeimo** [comment] 2022-06-10 17:51
- [ ] 1. For the conda env step, user should do that from the local repo directory- this is not mentioned in the RTD guide.

game plan: add how to open a project from Vscode (in that way the working directory should be at the local repo directory.)

**Comment by kefeimo** [comment] 2022-06-10 17:55
- [ ] 2.  Add notes about conda environment not activating correctly and how to fix it

I am not exactly sure what "not activating correctly", does it mean the terminal does not recognize "conda" command like "conda activate tsdat-pipelines"? In any case, will add reference to direct conda-related issues to conda documentation.

**Comment by kefeimo** [comment] 2022-06-10 18:08
- [ ] 5.  When making cookies, it appears there are some default or generated suggestions appear to the left of the colon. It’s not clear if just hitting enter accepts these defaults or they actually need to be typed in

For reference:
* Note that I (as Mark) do have a draft PR nearly ready to address and expand on the last point: [https://github.com/tsdat/pipeline-template/pull/22](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftsdat%2Fpipeline-template%2Fpull%2F22&data=05%7C01%7Ckefei.mo%40pnnl.gov%7Cc972bab805734013c64f08da4a4e57e2%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637903997588151471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XqC2oa3O73Es2J0HgroLXogqYxGXHjjeIDZcqLIPGFk%3D&reserved=0),
* see discussion in https://github.com/tsdat/pipeline-template/issues/4, especially the part "To mitigate this, I have played with some walkaround to add instruction to the question prompt. Though the solution is not pretty, I hope it can improve user experience by including instructions."

Retrospect: this is a technical debt by using CookieCutter at this point--it is hard to [Include help/instructions in cookiecutter prompts](https://www.guidodiepen.nl/2021/05/include-help-instructions-in-cookiecutter-prompts/).

Quick-fix: add instruction in the RTD, e.g.,
![image](https://user-images.githubusercontent.com/28743873/173125464-722f0902-33b9-4f2d-9a27-9bbb4147d320.png)

**Comment by maxwellevin** [comment] 2022-06-10 18:46
> * [ ]  2.  Add notes about conda environment not activating correctly and how to fix it
> 
> I am not exactly sure what "not activating correctly", does it mean the terminal does not recognize "conda" command like "conda activate tsdat-pipelines"? In any case, will add reference to direct conda-related issues to conda documentation.

This was about a specific issue Robert encountered where he had run `conda activate tsdat-pipelines`, but `conda` didn't *actually* activate his environment and was still using the system python, even though he had the little `(tsdat-pipelines)` thing next to his prompt in the terminal. This can sometimes happen if you have many conda environments open simultaneously, or if you open the same conda environment in multiple terminal windows, but I've also seen it happen somewhat randomly. Not sure why

**Comment by kefeimo** [comment] 2022-06-10 18:59
> 

This is so interesting to me. Not sure why either. But just for future exploration, run `which python`, `which conda` where the inconsistency happened, from there we might inspect what the cause is. (My guess is he has multiple conda installed without noticing.)

**Comment by maxwellevin** [comment] 2022-06-16 18:54
@kefeimo are you still working on any tasks related to this? If so I will keep this issue open until those are completed, otherwise I will close it.

**Comment by kefeimo** [comment] 2022-06-16 19:42
Please go ahead and close it. Let me know if I should close it next time, or PR an automatic issue-closing action after merging to main

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2022-06-16 19:47 UTC
Labels: documentation
